### ISSUE TITLE
IE 8 support?

### ISSUE THREAD

**Issue by BorntraegerMarc** [hotforfeature/origami#15]
Hi @hotforfeature 
We need to support browsers down to IE 8. If I understand it correctly, this lib does not support versions earlier then IE 11, correct? If yes: Why not?

Cheers,
Marc

**Comment by hotforfeature** [comment]
[Angular 2 only supports IE9 and up](https://angular.io/docs/ts/latest/guide/browser-support.html) and [Polymer 2 only supports IE11](https://www.polymer-project.org/2.0/docs/browsers). Unfortunately it is not possible to use either on IE8, which is why this repo cannot support it.

While Angular 2 can work on IE9 and IE10, Polymer 2 will not. That's why the supported version is only IE11.
