### ISSUE TITLE
Update production build docs

### ISSUE THREAD

**Issue by hotforfeature** [hotforfeature/origami#20]
The latest polymer-cli works a lot better with `index.html` as the entrypoint. I've found that the new best way of building for production is to have the index as the entrypoint, and `elements.html` as the shell.

Particularly, this setup fixes changes when compiling for ES5. In the old setup, you'd get errors about `babelHelpers` being undefined since that global was added to `elements.html`, which loads async before the other JS files.

**Comment by BorntraegerMarc** [comment]
Did you hear something about this problem https://polymer.slack.com/archives/C43V0TGLS/p1493821068411959?thread_ts=1493682810.197387&cid=C43V0TGLS ?

Pasting the problem again here for referencing reasons (should I maybe even create a new issue?):
Currently we use a weird mix of polymer-build and angular webpack magic to get the production build working. Maybe an extension to the angular-cli build would be the answer...

I still trying to figure out how to use a hash when building the polymer parts. Basically what Angular does:
- build sources and create new file names as a hash. for example: `[hash].bundle.js`
- Reference that hash in the generated `index.html`
Now if the browser fetches `index.html` it will receive the notification that the cached version and the stored version is not byte identical and trigger an update. (because the new `[hash].bundle.js` got changed. This is a quite normal best practice when working with cache in web browsers

I wanted to apply the concept to the polymer build. So probably something like this https://github.com/sindresorhus/gulp-rev would need to be used. Basically:
- Specify the entrypoint is `elements.html`
- Generate `[hash].elements.html` with all the other imports hashed as well
- AND not comes the tricky part: Reference that `[hash].elements.html`in our `index.html`. Which is generated through Angular

Because angular theoretically does not "know" about the polymer build it is difficult to include the generated `[hash].elements.html` for the prod build. I already found some work around, which work OK. But if someone wants to really build a correctly cached + managed production web app, this would be a mandatory step...

**Comment by BorntraegerMarc** [comment]
maybe even using something like https://css-tricks.com/combine-webpack-gulp-4/

**Comment by hotforfeature** [comment]
I did see that problem, though the major reasons I'm trying to avoid custom build configs (even if they start from ejecting Angular's build) are

1. Updates to how the Angular CLI creates its configuration would be lost
2. We're not all power users 😢

I think in the ideal world, we would be able to hook into or extend Angular's CLI to add polymer build as a step and reap all the benefits. That would require quite a bit of convincing from the Angular CLI team though.

I created this issue more focused on the `"entrypoint": "dist/assets/elements.html"` setup that I currently have, which will create problems when compiling JS to ES5 through the Polymer cli.

**Comment by BorntraegerMarc** [comment]
I thought it is in the roadmap of Angular to allow custom builds? Nonetheless I see it as a mandatory point in the documentation from this library to at least describe one possible solution. Even if it's not perfect. This is what I have been investigating now.

So my idea: try to push custom builds even further for Angular CLI and add documentation here on how to combine angular-cli & polymer-build. I already have some"hacky" solutions...

**Comment by hotforfeature** [comment]
I could be wrong, most issues I've seen about custom builds in the CLI on Angular's repo have been met with strong opposition. If that mentality has changed, it's good news.

Do you think you could throw together some of your ideas with custom exported builds in a branch?

**Comment by BorntraegerMarc** [comment]
I'm also not quite sure on that roadmap topic, to be honest.

I can do that. Do you want it in a branch or even a new project hotforfeature/origami-build?

**Comment by hotforfeature** [comment]
Branch it for now, I'd add a new folder like `demo-custom-build`. We could even combine things into an `examples` folder and have a different projects to highlight features between Angular 2 and Polymer instead of one massive demo folder.

If we like the tooling we create, then we could talk about separating it into its own project.

**Comment by BorntraegerMarc** [comment]
Sounds good

**Comment by BorntraegerMarc** [comment]
OK, after some digging around I think we should include a example on how to use the origami demo project without the scaffolded project using `ng new projectname`. So basically include a demo on how to build an angular project by using pure webpack configs. Here some reasons:

- If we want to include a "real" custom build we can anyhow not use angular-cli, because we need to add configs like `SWPrecacheWebpackPlugin`. (side note: maybe use https://github.com/angular/mobile-toolkit/tree/master/service-worker/worker to bring it to work)
- We need to use plugins for certain edge cases. For example:
```
    plugins: [
        new webpack.LoaderOptionsPlugin({
            options: {
                htmlLoader: {
                    // First the tag name and then the attribute name
                    attrs: ['iron-image:src', 'iron-icon:src', 'paper-icon-button:src']
                }
            }
        })
    ]
```

@hotforfeature I had a problem that I needed to add this plugin else when I included a tag with `iron-image src="some-source.png"` would not get loaded. Do you think this issue would also arise by using origami?

**Comment by hotforfeature** [comment]
I would not be opposed to setting up an example project that isn't scaffolded. As far as the iron-image, are you included `some-source.png` as part of the component's folder? I would assume it'd live inside the `assets/` folder.

If it is in the component's folder, or somewhere in `src/`, then yea I'm not sure how Webpack would know about it. Does the Angular CLI handle that?

**Comment by BorntraegerMarc** [comment]
you were right! After putting it in `assets` the angular-cli picked it up. My problem was that before I used webpack only...

**Comment by hotforfeature** [comment]
I fixed the original issue I had with the production docs. @BorntraegerMarc do you want to create a separate issue specifically to research and create a demo for custom webpack builds?

**Comment by BorntraegerMarc** [comment]
Created https://github.com/hotforfeature/origami/issues/25 this issue can be closed then :)
