### ISSUE TITLE
Remove my-custom-checkbox from examples

### ISSUE THREAD

**Issue by DaveMonag** [hotforfeature/origami#40]
Hello, I'm new to Polymer and Origami.

I'm going through the example code in the main readme, and you seem to use an element called "my-custom-checkbox" which doesn't seem to be mentioned anywhere or included in Origami, so when used by anyone just wanting a quick demo it will be absent. 
Example:
`<my-custom-checkbox [(checked)]="isChecked" emitChanges></my-custom-checkbox>`
from
https://github.com/hotforfeature/origami#markup

Am I missing something obvious, or is it just unnecessary code?
Cheers in advance

**Comment by DaveMonag** [comment]
Also the main Readme seems to give two sets of different instructions for seemingly the same job. In the installation part it says do one thing, then the "quick start" section gives different instructions. 
Also lines such as "Currently Origami only supports event binding, not data binding" at the end of installation seem to be misleading as data binding is listed as completed. So maybe a rework of the main readme is needed :)

**Comment by hotforfeature** [comment]
The `<my-custom-checkbox>` element is intended, and that code snippet is a reference, not a demo. It's important because it shows a developer how to make their own custom elements work when an Origami collection doesn't exist for them.

"Currently Origami only supports event binding, not data binding." is under the Polymer templates/Host Events section and refers to binding within Polymer templates. I could update that sentence to specifically re-mention Polymer templates incase someone scans through it.

The README does have two sections: a detailed step-by-step installation guide, and a shorter quick reference for those who have set up Origami before, but need a refresher. I do agree that it could be simplified.

**Comment by DaveMonag** [comment]
Ok thanks for clarifying :)
