### ISSUE TITLE
Update form docs to show reactive form example

### ISSUE THREAD

**Issue by BorntraegerMarc** [hotforfeature/origami#46]
For example: Does in the HTML template still the `value` property needs to be set when the form is initiated like:
```
this.editProfileForm = this.fb.group({
           firstName: [this.sharedService.loggedInUser.firstName, Validators.required]
       });
```

**Comment by BorntraegerMarc** [comment]
@hotforfeature maybe you could just write some quick notes in this issue and I will formulate and work out the docs. So you don't need to do everything yourself 😄

**Comment by hotforfeature** [comment]
Reactive forms should work pretty much exactly like they would with native elements. You add `formControlName` and `formGroupName` directives and do not set the value/disabled properties. Reactive forms will manage both.

The difference coming from Polymer is that you shouldn't use `<iron-form>`, since Angular's forms will be doing all of the work `<iron-form>` was doing. They'd just conflict with each other.

Another thing to note is that `<paper-button>` won't automatically submit forms. This also a  problem in Polymer with `<iron-form>` and it bears repeating.

```ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'my-form',
  template: `
    <form #ngForm="ngForm" novalidate (ngSubmit)="formSubmit()">
      <paper-input formControlName="firstName" ironControl></paper-input>
      <paper-input formControlName="lastName" ironControl></paper-input>
      <paper-button (click)="ngForm.onSubmit($event)">Submit</paper-button>
    </form>
  `
})
export class MyForm {
  form: FormGroup;

  constructor(fb: FormBuilder) {
    this.form = fb.group({
      firstName: ['Default Value', Validators.required],
      lastName: {
        defaultValue: 'Disabled',
        disabled: true
      }
    });
  }

  formSubmit() {
    console.log(this.form.value);
  }
}

**Comment by BorntraegerMarc** [comment]
thx! you want me to update the docs or should we just leave this here and as soon as something pops up I write again?

**Comment by hotforfeature** [comment]
Up to you really. I've been delaying this because I want to rewrite basically all of the documentation to make it cleaner. New docs, new build, and deprecating old code will make Origami 2 a clean start for Polymer 3.

If you have the time and want to add it to the docs though, I'll accept PRs. It'll likely be several weeks to a couple of months before I have the time to do some spring cleaning.

**Comment by BorntraegerMarc** [comment]
Sounds great. In that case I'll just wait for the new docs of you and I'll manage with the info here :) thx again!

**Comment by BorntraegerMarc** [comment]
OK, another question popped up. Have this date picker:
```
        <vaadin-date-picker emitChanges ironControl #birthdayPicker initial-position="1960-06-01"
                            formControlName="birthday" label="Birthday">
        </vaadin-date-picker>
```

gets created like this:
```
        this.createRoomForm = this.fb.group({
            firstName: ['', Validators.required],
            lastName: ['', Validators.required],
            admissionCause: ['', [Validators.required, Validators.maxLength(this.admissionCauseMaxLen)]],
            gender: ['', [Validators.min(0), Validators.max(1)]],
            birthday: ['', []]
        });
```

When sending the form:
![image](https://user-images.githubusercontent.com/7549295/30566054-c6c8dcd4-9cca-11e7-8330-23e28a2d1aab.png)


you see that `this.createRoomForm.controls.birthday.valid` is marked `true` in the console. Although I thought when adding `ironControl` the valid property should be automatically mapped from polymer to angular. Am I missing something? @hotforfeature

**Comment by hotforfeature** [comment]
@BorntraegerMarc sorry for the delayed response, I'm swamped with a project right now, so I haven't had time to test it out.

I think you need to add validation to the form group in Angular though. I'm not sure why `IronControl` validation isn't coming across, but I never used it by itself in my tests without some sort of Angular validator alongside it.

Maybe try adding `Validators.required` and see if it makes the form invalid with invalid dates after that? This sounds like a bug.
