### ISSUE TITLE
Latest (1.3.0-beta.0) npm install seems to be the whole directory

### ISSUE THREAD

**Issue by DaveMonag** [hotforfeature/origami#49]
As such current imports don't work as they're now a layer lower than they should be. Did you intend this change or just accidentally upload too much?
What it was before (^1.1.1):
![image](https://user-images.githubusercontent.com/22819035/28581096-46224e36-7159-11e7-97a5-09a1d4fe82a2.png)

What is is now (1.3.0-beta.0):
![image](https://user-images.githubusercontent.com/22819035/28581117-52266f8c-7159-11e7-85c1-9379d250d458.png)

**Comment by hotforfeature** [comment]
That doesn't look right 😓 

I'll check the build and republish.

**Comment by hotforfeature** [comment]
Yup, it usually helps if I run `npm publish` in the correct directory... sorry about that. 1.3.0-beta.1 should be good to go.

**Comment by DaveMonag** [comment]
Haha we're only human after all.

**Comment by DaveMonag** [comment]
@hotforfeature So there's a new file structure now? I'm a bit confused by the new use of the nested scope, is this new functionality, or was this just a mistake?
![image](https://user-images.githubusercontent.com/22819035/28878187-6a462934-7796-11e7-9886-2304abba552f.png)

**Comment by hotforfeature** [comment]
Yes, the new structure follows the [Angular Package Format v4](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview). If you're confused on the file structure, I'd suggest looking at that document and reading the "File layout" section. You can also open up `node_modules/@angular/core` to see the similarities. 

Ultimately, you shouldn't need to worry about the js files since your build system will take care of that for you. The `package.json` specifies the entrypoints for different bundling systems such as webpack and rollup.

The only time you may need to point to a js file is for SystemJS, where you should resolve `"@codebakery/origami": "node_modules/@codebakery/origami/bundles/origami.umd.min.js"`
