### ISSUE TITLE
Vaadin-grid won't render properly in production

### ISSUE THREAD

**Issue by DaveMonag** [hotforfeature/origami#53]
In Development it looks like this and renders fine:
![image](https://user-images.githubusercontent.com/22819035/29173859-77bb2e38-7ddc-11e7-89ce-8cc4f9124560.png)

However

Deployed it looks like this:
![image](https://user-images.githubusercontent.com/22819035/29173831-65e0abe8-7ddc-11e7-91f3-a44bf1c8e434.png)

No errors in the console or in the build, other than the warning in the pic below.

When I started playing with Vaadin grid, I got the exact same rendering bug (in development), and fixed it by just directly ripping your bower.json and polymer imports html file, so I assume this might be something to do with dependencies? Any ideas if I'm doing something wrong or this just doesn't work in production?

Also on an unrelated note, this:
![image](https://user-images.githubusercontent.com/22819035/29174001-e84dd9de-7ddc-11e7-8e55-c0a8f689c0c6.png)

![image](http://i0.kym-cdn.com/photos/images/original/000/608/147/05a.jpg)
What do I believe?

**Comment by hotforfeature** [comment]
The first one telling you to use `<template>` is Origami's warning, the second one telling you to use `<ng-template>` is Angular's warning.

For this scenario, you need to use `<template>`, a normal template element since `<vaadin-grid>` doesn't understand `<ng-template>`s, which are used in Angular. Angular 2 allowed the use of regular template elements, which it converted to ng-template at compile time (legacy template option), but that feature has been almost deprecated in 4.

To fully deprecate it and stop Angular from consuming and converting templates, you need to bootstrap your code with `enableLegacyTemplate: false`

[main.ts](https://github.com/hotforfeature/origami/blob/master/demo/src/main.ts)
```ts
  platformBrowserDynamic().bootstrapModule(AppModule, {
    enableLegacyTemplate: false
  });
```

If that doesn't fix the problem, there may be more going on that I'm missing. Could you post a sample repo somewhere for me to look at?

**Comment by DaveMonag** [comment]
My main.ts already has that code in it:
![image](https://user-images.githubusercontent.com/22819035/29177141-c179d886-7de5-11e7-92a3-ad8d5723d5ff.png)
So that _shouldnt_ be a problem. The code I'm using here is directly taken from your kitchen sink demo, but just the vaadin-grid part. 
![image](https://user-images.githubusercontent.com/22819035/29177314-4f0eedbc-7de6-11e7-8e5b-a3aa0a71736b.png)

I shouldn't have to do the manual change in vaadin-grid-column.html should I? It looks like that change is already in my version of vaadin-grid from the code from this commit: 
https://github.com/vaadin/vaadin-grid/commit/77b1fa3cee4c2176f63976b6e369d5eb5e261328#diff-7e6184d55472559417b6d689d28c80db

**Comment by hotforfeature** [comment]
Looks like my PR to the Angular repo fixed the issue with `enableLegacyTemplate` for the JIT compiler, but not the AOT compiler. I've submitted an issue (angular/angular#18639) and I'll work on another PR.

## Workarounds!

### Option 1

Use the JIT compiler in the meantime until the bug is fixed in Angular. Not the greatest, but if you're only in dev stage and not pushing to production, it may not be a big deal.

### Option 2

Use the old `<ng-template polymer>` and ignore the console warnings from Origami to make it work.

The slight downside is that the grid is expecting to see `class="header"` for column header templates, so while all the columns are there they don't have a header.

I'm not forwarding attributes from the `<ng-template>` to the `<template>` at runtime, but that could be fixed. I really don't like the idea of adding a feature to something that's deprecated, but that may be way faster than getting a PR through the Angular team :(

**Comment by hotforfeature** [comment]
According to the Angular team:

"Options for AOT have to be specified in the tsconfig.json"
```
{
  "compilerOptions": {
  // ...  
   },
  "angularCompilerOptions": {
    "enableLegacyTemplate": false
  }
}
```

I wasn't aware of that, so good to know. I'll be able to verify it tomorrow, but I'm keeping this issue open to remind me to add documentation on that to the README.

**Comment by DaveMonag** [comment]
I am pushing to production though, that's the entire problem. Work in Dev, doesn't in Production. Adding that compiler option didn't seem to change anything either, same result. Maybe I'm doing something else wrong. I'm glad I accidentally helped solve a problem you didn't know you had though!

**Comment by DaveMonag** [comment]
I am at least getting an error now, not a clue what it really means though:
![image](https://user-images.githubusercontent.com/22819035/29210281-bbff8b9e-7e8a-11e7-90ca-e215fb699098.png)

**Comment by DaveMonag** [comment]
Ignore that last error, not sure where it came from but it's gone now and I don't know why. Anyway, I added that compiler option to the **tsconfig.app.json** instead and that got things working on production. 
Cheers!

**Comment by hotforfeature** [comment]
Sounds good, I've added documentation to the README and updated the demo app to reflect the changes.
