### ISSUE TITLE
Weird Activity on Edge - Lazy & Slow 

### ISSUE THREAD

**Issue by first87** [hotforfeature/origami#55]
I am not sure if this issue is more related with Angular or Polymer.

My app is primarily built in Angular 4 + Polymer 2 which are bridged by `origami`.
The app has a list of channels and it loads a list of messages dynamically based on the selected channel. Everything works fine on all browsers including IE 11 but on Edge browser the app is running so lazy.

* selecting a channel doesn't work immediately, but delayed, on only Edge browser
  ```html
  <channel (channelSelect)="selectedChannel = $event">
    <!-- channel implementation -->
      <iron-selector #channelSelector>
        <paper-item ... ></paper-item>
      </iron-selector>
  </channel>
  ...
  <msg-list *ngIf="selectedChannel" [channel]="selectedChannel">
    <!-- msg-list implementation -->
      <msg *ngFor="let msg of msgs" [msg]="msg">
      </msg>
  <msg-list>
  ```
  selecting a channel will fire a custom event and update custom attribute on `<msg-list>`, this will lead `msgs` refreshed based on the selected channel and thus `<msg>`s will be loaded. This activity runs immediately on all browsers, but not on only Edge

* the app contains several blocks which needs to be displayed conditionally and so are controlled by `ngIf` ~ but they're all delayed shown on Edge only
  ```html
  <paper-button (click)="showBlock = !showBlock">Show/Hide</paper-button>
  <div *ngIf="showBlock">
    ...
  <div>
  ```

I tried to search any similar issue related with Angular, but not found anything. And the size of messages to load (and to render by `*ngFor`) is less than 15 right now so I guess the performance is not a problem.

**Comment by hotforfeature** [comment]
This problem seems to be pretty specific to your app, I don't see anything related to Origami in the markup you provided: no two-way databinding to a Polymer element or Angular/Polymer template sharing. Is there something you suspect Origami is doing to cause the sluggish behavior?

IE11 and Edge both are loading some heavy polyfills, that might be a good place to start debugging. Force Shady DOM to load on Chrome and see if you get similar behavior. There may also be some unintended loops happening (a custom event updates an attribute, which fires an event, which updates an attribute, etc, etc) that cause a perceived slow response.

Outside of those two areas to start looking in, I'd recommend stripping down other pieces of code until you're left with the bare minimum that causes an issue. That may present the answer itself, or you could publish it on plunker.

**Comment by BorntraegerMarc** [comment]
Can be closed, because webcomponentsjs had version 1.0.1. After upgrading to 1.0.10 it works

**Comment by hotforfeature** [comment]
@first87 can you confirm upgrading to webcomponentsjs 1.0.10 solves this problem for you?

**Comment by BorntraegerMarc** [comment]
I work on the same project as @first87 so it solved the problem for both of us :)

**Comment by hotforfeature** [comment]
Ah alright, I'll go ahead and close this then.
