### ISSUE TITLE
Angular + Polymer build process

### ISSUE THREAD

**Issue by jaichandra** [hotforfeature/origami#58]
I was looking at the production build docs on origami and got a little curious on the process. We are building the angular app using `angular-cli` and then running the compiled angular app through `polymer-cli` again. I understand what we are trying to accomplish here.
But I was wondering if this is the only way around and inverting this process (build polymer and inject to angular) didn't work.

This is what I think would be ideal.
1. Bundle Polymer elements separately - could be done using either `polymer-bundler` or `polymer-cli` (for ES5 bundle).
2. Configure `.angular-cli.json` to ignore `bower_components/` files completely, or include specifics as necessary for the angular app.
3. Use the generated polymer elements bundle file in angular app (point to `elements.bundle.html` directly in `index.html`) and build it using `ng build --prod`.

For this the `polymer.json` can point directly to `src/assets/elements.html` as `entrypoint`. I am also looking at writing a custom build file based on `polymer-build` so that bundling can be automated with `angular-cli` build.

The above looks less intrusive than running a complete angular app through the `polymer-cli`.
Thoughts?

**Comment by hotforfeature** [comment]
You could essentially do it either way, bundle first or compile first, the end result is the same. I went with compile first for two reasons:

1. You don't *need* to bundle in order to serve the project in development. You can run `ng serve` and everything will work, with bundling via the Polymer CLI being a production optimization. You'd have to re-bundle every time Polymer elements changed in development.

2. Polymer CLI generates multiple builds, such as bundled vs unbundled, which is great for the PRPL pattern. Angular only generates one build, and you'd always have the bundled variety.

Finally, the only Angular stuff that goes through the Polymer CLI would be minification and transpiling. Angular CLI already does this, and while it's not optimal to run the JS files through another round of it, I decided that the extra build time was worth the above two conveniences.

Ultimately though, my build process for Angular and Polymer has drastically changed with [polymer-webpack-loader](https://github.com/webpack-contrib/polymer-webpack-loader), and updating the build docs and sample app is on my todo list as soon as time permits.

I touch briefly on this process in #57, but the gist is that using the webpack loader we can import Polymer elements as ES modules into the individual Angular components that consume them. At build time these are bundled into the JavaScript chunks that Angular generates.

The end result is that you don't need the Polymer CLI at all and you can use all of the chunking, lazy loading, and ng service worker features of the Angular ecosystem that were difficult to incorporate in the current build process.

As a bonus, the build process would remain identical for Polymer 3, which will be written using native ES modules.

My current company's project uses this new build process with a custom fork of the Angular CLI to allow custom loaders. It works beautifully. What I'd love to see is for the Angular CLI team to add the hooks/customizations that they've talked about so that we can inject the polymer-webpack-loader into the build process. The alternative is using `ng eject`, which I don't prefer since you lose a lot of the `ng` CLI bonuses.

**Comment by jaichandra** [comment]
Awesome @hotforfeature! I was hoping to use `polymer-webpack-loader` but realized that `angular-cli` doesn't support any custom loaders. 
Are you also support IE11 in your project and all this works fine there? That seems to be my biggest sore point right now.
How long do we have to wait for your new build process :) If not elaborate documentation, is there some thing to refer to right now?
Thanks again for the excellent work you did with this library

**Comment by BorntraegerMarc** [comment]
I'm using IE11 with polymer 2 and angular 4 without problems :)

**Comment by hotforfeature** [comment]
Yup IE11 is supported, though we're working through some style issues with ShadyCSS at the moment.

I'm anxious to get this out there and documented, I'll try to at least update the demo app with the new process I'm currently using so you can steal ideas from that.

**Comment by hotforfeature** [comment]
Closing since this discussion is for an old iteration of Origami's build system, which has been overhauled in documentation for v3
