### ISSUE TITLE
Remove deprecated features

### ISSUE THREAD

**Issue by hotforfeature** [hotforfeature/origami#62]
The following features have been deprecated and are giving warnings of their deprecation. With a major change in v2, they should be removed.

- CustomStyleService
- `<ng-template polymer>`

As a side effect, this would increase the version requirement for Origami from Angular 4.0.0 (2017-03-23) to 4.2.0 (2017-06-08).

**Comment by alexeygt** [comment]
No problem with upgrading angular up to the latest 4.4.4.
HOWEVER, literally a day ago we tried to upgrade @angular/cli from v1.3.2 to latest 1.4.x - and it seems that PolymerDomSharedStylesHost doesn't work correctly anymore. Also, one of our views that uses vaading-grid with templates don't show templated content anymore.

**Comment by hotforfeature** [comment]
Hm, I have not tested 1.4 on the Angular CLI. We're using 1.3.2 for our project, and my initial tests with 1.5-beta were working.

I'll try updating to 1.4.4 on our project to see if anything breaks.

**Comment by alexeygt** [comment]
By the way - we confirm that starting from CLI v 1.4.0 our styling doesn't work correctly. We have tried latest 1.5.0-beta.2 and it doesn't work either, vaadin-grid templates don't work too. I suspect it has something to do with post-css as 1.5.0-beta.2 fires tons of warning like this:

WARNING in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./src/styles.css
(Emitted value instead of an instance of Error) postcss-custom-properties: ..\ExManager.FrontEnd\src\styles.css:14:3: Custom property ignored: not scoped to the top-level :root element (body { ... --application-foreground-color: ... })
NonErrorEmittedError: (Emitted value instead of an instance of Error) postcss-custom-properties: ..\ExManager.FrontEnd\src\styles.css:14:3: Custom property ignored: not scoped to the top-level :root element (body { ... --application-foreground-color: ... })
    at Object.emitWarning (..\ExManager.FrontEnd\node_modules\@angular\cli\node_modules\webpack\lib\NormalModule.js:117:16)
    at ExManager.FrontEnd\node_modules\postcss-loader\index.js:131:24
    at Array.forEach (native)
    at ExManager.FrontEnd\node_modules\postcss-loader\index.js:130:31
 @ ./src/styles.css 4:14-134
 @ multi ./src/styles.css
