### ISSUE TITLE
host events get fired multiple times

### ISSUE THREAD

**Issue by eikw** [hotforfeature/origami#72]
Hi,
i started my first project with angular and polymer and found this project very helpful but i found a bug in regards to host events.

I use a vaadin-grid and added some action-buttons(paper-button) to delete elements but every time i refresh the list, my on-click events of the buttons get fired multiple times(count of table-entries).
The code for this is similar to the example for host events in the documentation.
```html
<vaadin-grid>
   <vaadin-grid-column>
      <template class="header">Actions</template>
      <template ngNonBindable [polymer]="this">
        <paper-button raised on-tap="[[delete(item)]]">Delete</paper-button>
      </template>
    </vaadin-grid-column>
</vaadin-grid>
```
Is this only for computed attributes or can i use this as advertised in the documentation?

Thanks in advance

**Comment by hotforfeature** [comment]
I don't believe you can use computed event listeners in Polymer, that's just an Angular thing. Additionally, if you're on Polymer 2 I'm not sure Hammer.js is included by default to use the tap event (the new recommendation is to use `on-click` instead of `on-tap`).

```html
<vaadin-grid>
   <vaadin-grid-column>
      <template class="header">Actions</template>
      <template ngNonBindable [polymer]="this">
        <paper-button raised on-click="delete">Delete</paper-button>
      </template>
    </vaadin-grid-column>
</vaadin-grid>
```
```ts
delete(e) {
  const item = e.model.item;
}
```

The reason your "events" are being fired for each element is because Polymer is evaluated `delete(item)` and setting that to the `on-tap` attribute for each item instead of creating an event listener for each item.

**Comment by eikw** [comment]
Thanks for the quick response!
Everything works fine now.
I think this could also be documented to prevent similar questions.
