### ISSUE TITLE
Instead of `path-cli`, couldn't we use `ng eject` istead?

### ISSUE THREAD

**Issue by David-Mulder** [hotforfeature/origami#81]
Note: Angular 6 changes this to use the new angular.json format, which is confusing me greatly at the moment.

**Comment by hotforfeature** [comment]
Yup, instead of patching the CLI you could eject it and add the modifications. The reason I went with patching the CLI is to keep support for all of the `ng` commands. The last time I experimented with `ng eject`, I lost the ability to do simple things like `ng serve`. That, simplicity for adoption, and additional complications were the reason I went the patch route.

If the CLI has changed to better support ejecting, I'd love to hear about it! Ultimately though, the patch will be rendered useless with Polymer 3's release. The patch performs two goals:

1. Injecting polymer-webpack-loader to import HTML elements.
2. Suppressing CSS warnings about custom variables.

Polymer 3's use of ES modules and movement away from HTML imports with solve 1. 2 has already been solved in a later version of the Angular CLI, but is still there for backwards compatibility.

**Comment by David-Mulder** [comment]
My 'problem' was mostly that I was trying to get it to work with `angular.json` and that's when the 'patch' approach is frustrating. But if Polymer 3.0 makes all this obsolete (considering it's launching yesterday or today) I guess that that's not too much of an issue.

**Comment by hotforfeature** [comment]
Precisely. While Angular 6 is 100% on my radar, I'm holding off on any major decisions until after IO and Polymer 3's announcement. Then I'll start my investigation into what'd be the best path, keeping backwards compatibility in mind.

**Comment by hotforfeature** [comment]
Closing since v3 no longer patches the CLI
