### ISSUE TITLE
Docs: Zone.js doesn't play nice with webcomponents

### ISSUE THREAD

**Issue by David-Mulder** [hotforfeature/origami#82]
Maybe **_very_** useful to warn users that zone.js randomly (it's a race condition depending on who polyfills certain functions first) stops working in Edge/Firefox if you load webcomponents-loader.js . No idea how you didn't encounter this issue, but here is the relevant Github issue:

https://github.com/webcomponents/webcomponentsjs/issues/838

and

https://github.com/angular/zone.js/issues/782

There is a webapis-shadydom.js 'patch' you need to apply to zone.js for it to work.

**Comment by hotforfeature** [comment]
Are you using [webcomponentsReady()](https://github.com/hotforfeature/origami/blob/master/origami/src/util/webcomponents.ts#L37-L42) from this library? I have run into that and the crux of the problem was that the webcomponent polyfills were overriding the Zone.js Promise, which sends notifications to Angular.

That utility method will restore the global Promise after loading webcomponent polyfills.

**Comment by David-Mulder** [comment]
Two weeks late reply, but yeah, I was using that... though I did at one point whilst debugging this problem replace it with the "native" event, so I am somewhat confused what happened. Anyway, if that function actively does stuff then I think it's not right to call it `WebComponentsReady` which sounds like `jQuery`-era event listener. Kind of confused what's going on here though, but hey, at least it works now for me :) .
