### ISSUE TITLE
IncludeStylesModule expects RouterModule to be imported.

### ISSUE THREAD

**Issue by cdchow** [hotforfeature/origami#87]
Hi,

As noted in the issue title, the IncludeStylesModule, which is bundled in the OrigamiModule, expects the RouterModule to be imported at some point. Simply adding it to my `app.module.ts` like this `RouterModule.forRoot([])` would address the issue.

See a truncated error log below:
```
ERROR Error: StaticInjectorError(AppModule)[Router]: 
  StaticInjectorError(Platform: core)[Router]: 
    NullInjectorError: No provider for Router!
```

For additional context, I'm working on a hybrid AngularJS/Angular application that uses `@uirouter/angular-hybrid`. Using RouterModule in any way (even importing it in an @NgModule) makes the app complain and error (a different error, related to RouterModule). In the meantime, I've broken down our OrigamiModule import and instead imported its constituent modules, but excluding the IncludeStylesModule.

Agnostic of my issue, it seems like any Angular app that uses UIRouterModule instead of the default RouterModule would encounter this same error with IncludeStylesModule. I do not have a direct ask but wanted to surface the hard dependency on RouterModule.

Thanks.

**Comment by asyncLiz** [comment]
Hi @cdchow! Yes, the `IncludeStylesModule` does require the Angular router, since it [prepares lazy-loaded components](https://github.com/hotforfeature/origami/blob/master/styles/src/modules/inject-styles.ts#L48-L56) to enable the use of Polymer style modules in them.

Your solution to not import `OrigamiModule` and instead import the individual modules you use is the correct one.

Is the request to document the `@angular/router` dependency more clearly, or find a solution that does not require it? Right now if someone uses `@uirouter/angular-hybrid`, they would be unable to use the `@IncludeStyles()` decorator.

It might not be a bad idea to think of ways to configure `IncludeStylesModule` to accept different types of routers outside of the Angular one, or to disable hooking into the Angular router entirely.

**Comment by cdchow** [comment]
Thanks @asyncLiz. Yes, exactly that, to document the dependency more clearly. 🙏

**Comment by asyncLiz** [comment]
I've added more documentation, as well as an alternative `IncludeStylesNoRouterModule` that can be used instead of the one that requires `@angular/router`.
