### ISSUE TITLE
routerLink within <template>

### ISSUE THREAD

**Issue by Yavin** [hotforfeature/origami#92]
version: 3.1.1
angular: 8.2.2

I have problems using `routerLink` inside polymer `template`.

```
<vaadin-grid [items]="items">
  <vaadin-grid-column path="filename">
    <template ngNonBindable>
      <a routerLink="/browse/[[item.filename]]" routerLinkActive="active">
        [[item.filename]]
      </a>
    </template>
  </vaadin-grid-column>
</vaadin-grid>
```
![](https://i.imgur.com/lz20Z7o.png)

links are displayed, but angular doesn't process them.

in dom they are visible like this:
```
<vaadin-grid-cell-content slot="vaadin-grid-cell-content-4">
      <a _ngcontent-mtf-c1="" routerlinkactive="active">
        aaa
      </a>
</vaadin-grid-cell-content>
```
in console there is only warning `Lazy routes discovery is not enabled. Because there is neither an entryModule nor a statically analyzable bootstrap code in the main file.`, but I don't know if it is related.

if I remove `ngNonBindable` attribute links are working...
```
<template>
      <a routerLink="/browse/[[item.filename]]">
        [[item.filename]]
      </a>
</template>
```

but they are pointing to `/browse/[[item.filename]]`
```
<vaadin-grid-cell-content slot="vaadin-grid-cell-content-4">
      <a _ngcontent-tvi-c1="" routerlinkactive="active" ng-reflect-router-link-active="active" href="/browse/%5B%5Bitem.filename%5D%5D">
        aaa
      </a>
</vaadin-grid-cell-content>
```

**Comment by asyncLiz** [comment]
Angular components, syntax, and directives like `[routerLink]` cannot be used in Polymer templates. That's because Polymer doesn't know how to instantiate them correctly, that's why we add `ngNonBindable`.

You'll have to think of another way to get your URL in the template. I'd suggest [generating the URL](https://angular.io/api/router/Router#createurltree) and providing that to your component. Looks like you're using vaadin-grid, so a property on each item would do well.

```ts
item.url = this.router.createUrlTree(['/browse', item.filename]).toString();
```

Then you can use Polymer's syntax binding to access it.

```html
<template>
  <a href="[[item.url]]">[[item.filename]]</a>
</template>
```

If you need it to be more dynamic, you can use Origami's logic of adding event listeners to call an Angular method on your component.

```html
<template>
  <a href="[[getNgRoute(item)]]">[[item.filename]]</a>
</template>
```

You can read more about what you can and can't do in Polymer templates in [templates/README.md](https://github.com/hotforfeature/origami/blob/master/templates/README.md)
